#!/usr/bin/env node
// ECZ-ID Plugin Foundry: generate every plugin and both marketplace catalogues
// from the shared product facts and the plugin definitions. Deterministic and
// idempotent: running it twice produces byte-identical output, and CI fails if
// the committed output drifts from the generator.
//
// Portable-first: each plugin is an Agent Plugins 1.0.0 package (plugin.json,
// skills/, mcp.json) and also carries the Claude Code manifest
// (.claude-plugin/plugin.json, .mcp.json) so it installs in Claude Code, VS Code,
// Copilot CLI, and any host that reads Agent Skills + mcp.json.
import { mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const facts = JSON.parse(readFileSync(join(here, "product-facts.json"), "utf8"));
const defs = JSON.parse(readFileSync(join(here, "plugins.json"), "utf8"));
const engineSource = readFileSync(join(here, "review-engine.mjs"), "utf8");

const OUT = join(root, "plugins");
const AUTHOR = { name: facts.organisation.name, url: facts.urls.gateway };

/** {{a.b.c}} substitution from a context object; unknown keys fail the build. */
function fill(text, ctx) {
  return text.replace(/\{\{([a-zA-Z0-9_.]+)\}\}/g, (_, path) => {
    const v = path.split(".").reduce((o, k) => (o == null ? undefined : o[k]), ctx);
    if (v === undefined || v === null || typeof v === "object") throw new Error(`unresolved placeholder {{${path}}}`);
    return String(v);
  });
}
function fillDeep(value, ctx) {
  if (typeof value === "string") return fill(value, ctx);
  if (Array.isArray(value)) return value.map((v) => fillDeep(v, ctx));
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, fillDeep(v, ctx)]));
  return value;
}
const json = (o) => JSON.stringify(o, null, 2) + "\n";
function write(rel, content) {
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

const MCP_SERVERS = {
  verifier: {
    key: "ecz-id-verifier",
    agentPlugins: { type: "stdio", command: "npx", args: ["-y", `${facts.verifier.npm}@${facts.verifier.version}`, facts.verifier.stdioBin] },
    claude: { command: "npx", args: ["-y", `${facts.verifier.npm}@${facts.verifier.version}`, facts.verifier.stdioBin] }
  }
};

function reviewBundle(def, ctx) {
  const r = def.review;
  let spec, profile, syncedFrom = null;
  if (r.factsFile) {
    const f = JSON.parse(readFileSync(join(here, "facts", `${r.factsFile}.json`), "utf8"));
    spec = f.spec; profile = f.profile; syncedFrom = f.syncedFrom;
  } else {
    spec = fillDeep(r.spec, ctx); profile = fillDeep(r.profile, ctx);
  }
  return { spec, profile, syncedFrom, extraDotEntries: r.extraDotEntries ?? [] };
}

function reviewScript(bundle) {
  // Self-contained: engine + facts inlined, no imports beyond node built-ins.
  const engine = 'import { readdirSync } from "node:fs";\nimport { join, relative } from "node:path";\n' +
    engineSource.replace(/^import .*$/gm, "").replace(/^\/\/.*\n/gm, "");
  return `#!/usr/bin/env node
// ${bundle.spec.displayName}: portable evidence review (generated by the ECZ-ID Plugin Foundry; do not edit).
// Reads file NAMES and PATHS under the given root. Opens no file. No network. Writes nothing.
// Same detectors, Review Priority rules and next actions as the ECZ-ID VS Code extension.
${engine}
const SPEC = ${JSON.stringify(bundle.spec)};
const PROFILE = ${JSON.stringify(bundle.profile)};
const EXTRA_DOT_ENTRIES = ${JSON.stringify(bundle.extraDotEntries)};

const args = process.argv.slice(2);
const wantJson = args.includes("--json");
const root = args.find((a) => !a.startsWith("--")) ?? process.cwd();
const { resolve: resolvePath, basename } = await import("node:path");
const { statSync } = await import("node:fs");
const abs = resolvePath(root);
let st;
try { st = statSync(abs); } catch { console.error("not a directory: " + root); process.exit(2); }
if (!st.isDirectory()) { console.error("not a directory: " + root); process.exit(2); }
const files = listFiles(abs, { extraDotEntries: EXTRA_DOT_ENTRIES });
const result = detectEvidence(SPEC, files, basename(abs));
if (wantJson) console.log(JSON.stringify(projectReview(SPEC, result, PROFILE), null, 2));
else console.log(renderReview(SPEC, result, PROFILE));
`;
}

function pluginReadme(def, ctx, bundle) {
  const ext = def.vscodeExtension ? fillDeep(def.vscodeExtension, ctx) : null;
  const L = [];
  L.push(`# ${def.displayName} (agent plugin)`, "", def.description, "");
  L.push("Free. Local-first. Read-only. No source upload. No telemetry. Part of the ECZ-ID Machine Trust plugin estate: " + facts.organisation.estateUrl, "");
  L.push("## What it does", "");
  if (bundle) {
    L.push(`- Skill \`${def.skills[0]}\` runs a portable, filename-and-path-only evidence review (\`scripts/review.mjs\`) and reports EVIDENCE OBSERVED / NOT OBSERVED, a deterministic Review Priority (LOW / NORMAL / ELEVATED / HIGH) with the reasons, why each class matters and what to review next, plus at most three contextual next actions.`);
    L.push(`- Evidence classes: ${bundle.spec.detectors.map((d) => d.label).join("; ")}.`);
  } else {
    L.push(`- Skill \`${def.skills[0]}\` teaches the agent to use the read-only ECZ-ID Verifier tools correctly and to report ResultStates and ReasonCodes without turning them into a score.`);
  }
  if (def.mcpServers.length) L.push(`- MCP server \`${MCP_SERVERS.verifier.key}\`: \`${facts.verifier.npm}@${facts.verifier.version}\` over stdio, three read-only tools (${facts.verifier.tools.join(", ")}). Launched by the host with npx; nothing is installed globally.`);
  L.push("");
  L.push("## Install", "");
  L.push("**Claude Code**", "", "```", `/plugin marketplace add ${facts.organisation.estateRepo}`, `/plugin install ${def.id}@${facts.organisation.marketplaceName}`, "```", "");
  L.push("**VS Code and GitHub Copilot**: add `" + facts.organisation.estateRepo + "` to the `chat.plugins.marketplaces` setting, or run `Chat: Install Plugin From Source` with `" + facts.organisation.estateUrl + "`. Copilot CLI reads the same marketplace.", "");
  L.push("**Cursor, Codex CLI, Gemini CLI, Kiro and any Agent Skills host**: copy this plugin directory (or just `skills/`) into the host's skills location" + (def.mcpServers.length ? " and add the `mcp.json` server entry to the host's MCP configuration." : ".") + " The package is an Agent Plugins 1.0.0 plugin (`plugin.json`, `skills/`" + (def.mcpServers.length ? ", `mcp.json`" : "") + ").", "");
  if (ext) {
    L.push("## The same capability in VS Code", "");
    L.push(`**${ext.name}** for VS Code carries the same detectors, guidance and Review Priority, plus a shareable evidence summary and a local JSON + Markdown report: ${ext.marketplace} (Open VSX: ${ext.openVsx}). Product page: ${ext.page}`, "");
    if (ext.editions) {
      const eds = facts.editions[ext.editions];
      const dtp = facts.editions.developerTrustPro;
      L.push("### Editions (VS Code extension)", "");
      for (const e of eds) L.push(`- **${e.name}**: ${e.monthly}${e.annual !== e.monthly ? ` or ${e.annual}` : ""}. ${e.proposition}`);
      L.push(`- **${dtp.name}**: ${dtp.monthly} or ${dtp.annual}. ${dtp.proposition} Activate: ${facts.urls.developerTrustActivate}`, "");
      L.push(facts.editions.entitlementRule, "");
      L.push("**Capability parity, stated plainly:** this plugin inspects and routes in whatever host runs it. Mediation (the Local Trust Gate), retained history (Trust Epochs) and the other Pro capabilities run only in the VS Code extension. A plugin host cannot provide them, so this plugin does not claim them.", "");
    }
  }
  const actions = bundle ? bundle.profile.actions.map((a) => ({ label: a.label, url: a.url })) : fillDeep(def.nextActions, ctx);
  L.push("## Next actions it may offer (at most three per result)", "");
  for (const a of actions) L.push(`- ${a.label}: ${a.url}`);
  if (bundle?.profile.discovery) L.push(`- ${bundle.profile.discovery.label}: ${bundle.profile.discovery.url}`);
  L.push("");
  L.push("## Doctrine", "", ...facts.doctrine.map((d) => `- ${d}`), "");
  L.push("## Privacy", "", "- Reviews read file names and paths only; no file is opened, no SBOM is parsed, no secret value is read.", "- The Verifier MCP server, where configured, reads public Resolver posture only and sends no telemetry.", "- Nothing is written to your workspace unless you ask for the JSON output and redirect it yourself.", "");
  L.push("## Links", "", `- Documentation: ${facts.urls.gateway}`, `- Resolver (read-only public proof): ${facts.urls.resolver}`, `- TrustOps (setup and checkout): ${facts.urls.trustopsStart}`, `- Questions: ${facts.organisation.supportUrl}`, "");
  L.push(`Generated by the ECZ-ID Plugin Foundry. Agent Plugins ${facts.specs.agentPlugins}. License: ${facts.organisation.license} (the Verifier package carries its own licence).`, "");
  return L.join("\n");
}

function buildPlugin(def) {
  const ctx = { ...facts, plugin: def };
  const bundle = def.review ? reviewBundle(def, ctx) : null;
  const dir = def.id;
  const version = defs.version;

  // Agent Plugins 1.0.0 manifest
  write(`${dir}/plugin.json`, json({
    $schema: facts.specs.pluginSchema,
    name: def.id,
    version,
    description: def.description,
    author: AUTHOR,
    homepage: def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs,
    repository: facts.organisation.estateUrl,
    license: facts.organisation.license,
    keywords: def.keywords
  }));
  // Claude Code manifest (same identity)
  write(`${dir}/.claude-plugin/plugin.json`, json({
    name: def.id, version, description: def.description, author: AUTHOR,
    homepage: def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs,
    repository: facts.organisation.estateUrl, license: facts.organisation.license, keywords: def.keywords
  }));
  // MCP servers (both shapes)
  if (def.mcpServers.length) {
    const ap = {}, cl = {};
    for (const s of def.mcpServers) { ap[MCP_SERVERS[s].key] = MCP_SERVERS[s].agentPlugins; cl[MCP_SERVERS[s].key] = MCP_SERVERS[s].claude; }
    write(`${dir}/mcp.json`, json({ $schema: facts.specs.mcpSchema, mcpServers: ap }));
    write(`${dir}/.mcp.json`, json({ mcpServers: cl }));
  }
  // Skills
  for (const skill of def.skills) {
    let body;
    if (skill === "ecz-id-verify") {
      body = fill(readFileSync(join(here, "templates", "skills", "ecz-id-verify.md"), "utf8"), ctx);
    } else {
      const ext = fillDeep(def.vscodeExtension, ctx);
      const subject = bundle.spec.displayName.replace(/^ECZ-ID /, "");
      const audience = def.id.includes("dora") ? "a DORA supervisory, audit or customer request" : def.id.includes("sbom") ? "the CRA reporting window" : "a reviewer, platform or counterparty";
      const extra = def.mcpServers.length
        ? `## Public proof\n\nWhen the review reports an ECZ-ID public proof reference, or the user names an ECZ-ID, use the read-only Verifier tools this plugin configures (\`${facts.verifier.tools.join("`, `")}\`) and report the ResultState and ReasonCodes exactly as returned. Absence of public proof is neutral.`
        : `## Regulatory wording\n\nQuote the regulation only as the review text does (article numbers and dates verified against EUR-Lex). Never state that the user is compliant, certified or ready; describe evidence observed, evidence not observed and what to review next.`;
      body = fill(readFileSync(join(here, "templates", "skills", "review-common.md"), "utf8"), { ...ctx, review: { subject, audience, extra }, extension: ext });
    }
    const description = bundle
      ? `${bundle.profile.question} Runs a local, filename-and-path-only evidence review and reports EVIDENCE OBSERVED / NOT OBSERVED, a deterministic Review Priority with reasons, why each class matters and what to review next. Use when asked about ${bundle.spec.displayName.replace(/^ECZ-ID /, "")} evidence, readiness, gaps or what to review next in a repository.`
      : `Check the public ECZ-ID Resolver posture of an MCP server, agent, API, package, domain or business with the read-only ECZ-ID Verifier tools, and explain ResultStates and ReasonCodes without scoring. Use when asked to check, verify or look up an ECZ-ID or public proof.`;
    const fm = [
      "---",
      `name: ${skill}`,
      `description: ${description.replace(/\n/g, " ")}`,
      `license: ${facts.organisation.license}`,
      "metadata:",
      `  author: ${facts.organisation.publisher}`,
      `  version: "${version}"`,
      `  ecz-id-plugin: ${def.id}`,
      "---",
      ""
    ].join("\n");
    write(`${dir}/skills/${skill}/SKILL.md`, fm + body);
    if (bundle) {
      write(`${dir}/skills/${skill}/scripts/review.mjs`, reviewScript(bundle));
      write(`${dir}/skills/${skill}/references/evidence-classes.json`, json({ generatedFrom: bundle.syncedFrom ?? { definition: "foundry/plugins.json" }, detectors: bundle.spec.detectors.map((d) => ({ id: d.id, label: d.label, patterns: d.patterns })), guidance: bundle.profile.guidance }));
    }
  }
  write(`${dir}/README.md`, pluginReadme(def, ctx, bundle));
  return { def, version, homepage: def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs };
}

// ---- generate ----
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const built = defs.plugins.map(buildPlugin);

const entries = built.map(({ def, version, homepage }) => ({
  name: def.id,
  description: def.description,
  version,
  author: AUTHOR,
  homepage,
  repository: facts.organisation.estateUrl,
  license: facts.organisation.license,
  keywords: def.keywords,
  category: def.category
}));

const claudeMarketplace = {
  name: facts.organisation.marketplaceName,
  owner: { name: facts.organisation.name, url: facts.urls.gateway },
  metadata: { description: facts.organisation.marketplaceDescription, version: defs.version },
  plugins: entries.map((e) => ({ ...e, source: `./plugins/${e.name}` }))
};
const copilotMarketplace = {
  name: facts.organisation.marketplaceName,
  owner: { name: facts.organisation.name, url: facts.urls.gateway },
  metadata: { description: facts.organisation.marketplaceDescription, version: defs.version },
  plugins: entries.map((e) => ({ ...e, source: { source: "github", repo: facts.organisation.estateRepo, path: `plugins/${e.name}` } }))
};
mkdirSync(join(root, ".claude-plugin"), { recursive: true });
mkdirSync(join(root, ".github", "plugin"), { recursive: true });
writeFileSync(join(root, ".claude-plugin", "marketplace.json"), json(claudeMarketplace));
writeFileSync(join(root, ".github", "plugin", "marketplace.json"), json(copilotMarketplace));
writeFileSync(join(OUT, "index.json"), json({ generatedBy: "foundry/build.mjs", agentPlugins: facts.specs.agentPlugins, version: defs.version, plugins: entries.map((e) => ({ name: e.name, description: e.description, path: `plugins/${e.name}` })) }));
console.log(`built ${built.length} plugins -> plugins/, .claude-plugin/marketplace.json, .github/plugin/marketplace.json`);
