#!/usr/bin/env node
// ECZ-ID Plugin Foundry: generate every plugin and both marketplace catalogues
// from the shared product facts and the plugin definitions. Deterministic and
// idempotent: running it twice produces byte-identical output, and CI fails if
// the committed output drifts from the generator.
//
// Portable-first: each plugin is an Agent Plugins 1.0.0 package (plugin.json,
// skills/, mcp.json) and also carries the Claude Code manifest
// (.claude-plugin/plugin.json, .mcp.json) so it installs in Claude Code, VS Code,
// Copilot CLI, and any host that reads Agent Skills + mcp.json.
import { mkdirSync, readFileSync, writeFileSync, rmSync, existsSync, copyFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const facts = JSON.parse(readFileSync(join(here, "product-facts.json"), "utf8"));
const defs = JSON.parse(readFileSync(join(here, "plugins.json"), "utf8"));
const engineSource = readFileSync(join(here, "review-engine.mjs"), "utf8");

const OUT = join(root, "plugins");
const AUTHOR = { name: facts.organisation.name, url: facts.urls.gateway };

// OpenAI / Codex listing constants, fixed by the accepted 0.1.1 submission.
const OPENAI_CATEGORY = "Developer Tools";
const OPENAI_CAPABILITIES = ["Read"];
// Resolved from the plugin root in .codex-plugin/plugin.json and from the SKILL ROOT in
// skills/<skill>/agents/openai.yaml. Both spellings are "./assets/logo.png", so the logo
// is written twice: once at <plugin>/assets/ and once at <plugin>/skills/<skill>/assets/.
const OPENAI_ICON = "./assets/logo.png";
const OPENAI_PRODUCTS = ["CHAT", "CODEX"];

/** Double-quoted YAML scalar. The values here are plain ASCII prose; a control character
 *  or a non-ASCII byte is rejected rather than silently mangled. */
function yamlString(s) {
  if (/[^\x20-\x7e]/.test(s)) throw new Error(`unsupported character in YAML scalar: ${JSON.stringify(s)}`);
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
const lowerFirst = (s) => s.charAt(0).toLowerCase() + s.slice(1);

/** {{a.b.c}} substitution from a context object; unknown keys fail the build. */
function fill(text, ctx) {
  return text.replace(/\{\{([a-zA-Z0-9_.]+)\}\}/g, (_, path) => {
    const v = path.split(".").reduce((o, k) => (o == null ? undefined : o[k]), ctx);
    if (Array.isArray(v) && v.every((x) => typeof x === "string")) return v.join(", ");
    if (v === undefined || v === null || typeof v === "object") throw new Error(`unresolved placeholder {{${path}}}`);
    return String(v);
  });
}
function fillDeep(value, ctx) {
  if (typeof value === "string") return fill(value, ctx);
  if (Array.isArray(value)) return value.map((v) => fillDeep(v, ctx));
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, fillDeep(v, ctx)]));
  return value;
}
const json = (o) => JSON.stringify(o, null, 2) + "\n";
function write(rel, content) {
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

const MCP_SERVERS = {
  verifier: {
    key: "ecz-id-verifier",
    agentPlugins: { type: "stdio", command: "npx", args: ["-y", `${facts.verifier.npm}@${facts.verifier.version}`, facts.verifier.stdioBin] },
    claude: { command: "npx", args: ["-y", `${facts.verifier.npm}@${facts.verifier.version}`, facts.verifier.stdioBin] }
  }
};

function reviewBundle(def, ctx) {
  const r = def.review;
  let spec, profile, syncedFrom = null;
  if (r.factsFile) {
    const f = JSON.parse(readFileSync(join(here, "facts", `${r.factsFile}.json`), "utf8"));
    spec = f.spec; profile = f.profile; syncedFrom = f.syncedFrom;
  } else {
    spec = fillDeep(r.spec, ctx); profile = fillDeep(r.profile, ctx);
  }
  return { spec, profile, syncedFrom, extraDotEntries: r.extraDotEntries ?? [] };
}

function reviewScript(bundle) {
  // Self-contained: engine + facts inlined, no imports beyond node built-ins.
  const engine = 'import { readdirSync } from "node:fs";\nimport { join, relative } from "node:path";\n' +
    engineSource.replace(/^import .*$/gm, "").replace(/^\/\/.*\n/gm, "");
  return `#!/usr/bin/env node
// ${bundle.spec.displayName}: portable evidence review (generated by the ECZ-ID Plugin Foundry; do not edit).
// Reads file NAMES and PATHS under the given root. Opens no file. No network. Writes nothing.
// Same detectors, Review Priority rules and next actions as the ECZ-ID VS Code extension.
${engine}
const SPEC = ${JSON.stringify(bundle.spec)};
const PROFILE = ${JSON.stringify(bundle.profile)};
const EXTRA_DOT_ENTRIES = ${JSON.stringify(bundle.extraDotEntries)};

const args = process.argv.slice(2);
const wantJson = args.includes("--json");
const root = args.find((a) => !a.startsWith("--")) ?? process.cwd();
const { resolve: resolvePath, basename } = await import("node:path");
const { statSync } = await import("node:fs");
const abs = resolvePath(root);
let st;
try { st = statSync(abs); } catch { console.error("not a directory: " + root); process.exit(2); }
if (!st.isDirectory()) { console.error("not a directory: " + root); process.exit(2); }
const files = listFiles(abs, { extraDotEntries: EXTRA_DOT_ENTRIES });
const result = detectEvidence(SPEC, files, basename(abs));
if (wantJson) console.log(JSON.stringify(projectReview(SPEC, result, PROFILE), null, 2));
else console.log(renderReview(SPEC, result, PROFILE));
`;
}

/**
 * Routes that cost money, told apart from the free ones deterministically rather than by hand.
 * TrustOps owns acquisition, payment and entitlement (doctrine), so every TrustOps URL is a
 * commercial route; `kind: "product"` marks a priced ECZ-ID product wherever it is hosted.
 */
function isCommercialAction(a) {
  let host = "";
  try { host = new URL(a.url).host; } catch { /* relative or malformed: treated as free */ }
  return a.kind === "product" || host === "trustops.ecocitizenz.com";
}

/** The plugin public policy pages: support, privacy and terms, one live page per plugin. */
function policyPages(def) {
  const base = facts.compliance?.policyBase;
  if (!base || !def.policySlug) return [];
  const label = { support: "Support", privacy: "Privacy policy", terms: "Terms" };
  return (facts.compliance.pages ?? []).map((page) => ({
    page,
    label: label[page] ?? page,
    url: `${base}${def.policySlug}/${page}/`
  }));
}

function pluginReadme(def, ctx, bundle) {
  const ext = def.vscodeExtension ? fillDeep(def.vscodeExtension, ctx) : null;
  const paidExt = ext && ext.editions ? facts.editions[ext.editions] : null;
  const L = [];
  L.push(`# ${def.displayName} (agent plugin)`, "", def.description, "");

  // The free statement leads, because this is the line a marketplace reviewer reads first.
  L.push("## Free agent plugin. No purchase required.", "");
  L.push("No account, no sign-in, no licence key, no trial and no paywall. Every capability described below works in full as soon as you install it, in whatever host you run it in, for free.", "");
  L.push(`This plugin is open source under the ${facts.organisation.license} licence${def.mcpServers.length ? " (the ECZ-ID Verifier npm package it launches carries its own licence)" : ""}: ${facts.organisation.estateUrl}`, "");
  L.push("Local-first. Read-only. No source upload. No telemetry. No score. Part of the ECZ-ID Machine Trust plugin estate.", "");

  L.push("## What it does", "");
  if (bundle) {
    L.push(`- Skill \`${def.skills[0]}\` runs a portable, filename-and-path-only evidence review (\`scripts/review.mjs\`) and reports EVIDENCE OBSERVED / NOT OBSERVED, a deterministic Review Priority (LOW / NORMAL / ELEVATED / HIGH) with the reasons, why each class matters and what to review next, plus at most three contextual next actions.`);
    L.push(`- Evidence classes: ${bundle.spec.detectors.map((d) => d.label).join("; ")}.`);
  } else {
    L.push(`- Skill \`${def.skills[0]}\` teaches the agent to use the read-only ECZ-ID Verifier tools correctly and to report ResultStates and ReasonCodes without turning them into a score.`);
  }
  if (def.mcpServers.length) L.push(`- MCP server \`${MCP_SERVERS.verifier.key}\`: \`${facts.verifier.npm}@${facts.verifier.version}\` over stdio, three read-only tools (${facts.verifier.tools.join(", ")}). Launched by the host with npx; nothing is installed globally.`);
  L.push("");

  L.push("## Install", "");
  L.push("**Claude Code**", "", "```", `/plugin marketplace add ${facts.organisation.estateRepo}`, `/plugin install ${def.id}@${facts.organisation.marketplaceName}`, "```", "");
  L.push("**VS Code and GitHub Copilot**: add `" + facts.organisation.estateRepo + "` to the `chat.plugins.marketplaces` setting, or run `Chat: Install Plugin From Source` with `" + facts.organisation.estateUrl + "`. Copilot CLI reads the same marketplace.", "");
  L.push("**Cursor, Codex CLI, Gemini CLI, Kiro and any Agent Skills host**: copy this plugin directory (or just `skills/`) into the host's skills location" + (def.mcpServers.length ? " and add the `mcp.json` server entry to the host's MCP configuration." : ".") + " The package is an Agent Plugins 1.0.0 plugin (`plugin.json`, `skills/`" + (def.mcpServers.length ? ", `mcp.json`" : "") + ").", "");
  L.push("Nothing in any of those routes asks for payment, an account or a key.", "");

  const actions = bundle
    ? [...bundle.profile.actions.map((a) => ({ label: a.label, url: a.url, kind: a.kind })), ...(bundle.profile.discovery ? [bundle.profile.discovery] : [])]
    : fillDeep(def.nextActions, ctx);
  const freeActions = actions.filter((a) => !isCommercialAction(a));
  const paidActions = actions.filter(isCommercialAction);
  L.push("## What it may suggest next (at most three per result)", "");
  if (freeActions.length) {
    L.push("Free routes — free tools, free identity and documentation, nothing to buy:", "");
    for (const a of freeActions) L.push(`- ${a.label}: ${a.url}`);
    L.push("");
  }
  if (paidActions.length) {
    L.push("Optional paid ECZ-ID routes, offered only where they fit the result. **None of these is required.** This plugin is complete without them, nothing it does is withheld until you buy one, and it never runs checkout, sells a subscription or grants entitlement itself:", "");
    for (const a of paidActions) L.push(`- ${a.label}: ${a.url}`);
    L.push("");
  }

  L.push("## Doctrine", "", ...facts.doctrine.map((d) => `- ${d}`), "");
  L.push("## Privacy", "", "- Reviews read file names and paths only; no file is opened, no SBOM is parsed, no secret value is read.", "- The Verifier MCP server, where configured, reads public Resolver posture only and sends no telemetry.", "- Nothing is written to your workspace unless you ask for the JSON output and redirect it yourself.", "");

  // Anything with a price is described here, below the free plugin, and never above it.
  if (ext && !paidExt) {
    L.push(`## Optional: the same capability in the free VS Code extension`, "");
    L.push(`You do not need it — this plugin is complete on its own. **${ext.name}** for VS Code is free as well, and carries the same detectors, guidance and Review Priority, plus a shareable evidence summary and a local JSON + Markdown report: ${ext.marketplace} (Open VSX: ${ext.openVsx}). Product page: ${ext.page}`, "");
  }
  if (paidExt) {
    const dtp = facts.editions.developerTrustPro;
    L.push(`## Optional and separate: ${ext.name} for VS Code (a different product)`, "");
    L.push(`**You do not need this to use this plugin, and this plugin is not a trial of it.** ${ext.name} is a separate product — a VS Code extension, not this plugin. Nothing in this plugin is locked, limited, time-limited or degraded because you do not have it, and this plugin sells nothing.`, "");
    L.push(`It carries the same detectors, guidance and Review Priority, plus a shareable evidence summary and a local JSON + Markdown report: ${ext.marketplace} (Open VSX: ${ext.openVsx}). Product page: ${ext.page}`, "");
    L.push(`### Editions of that VS Code extension (not of this plugin)`, "");
    for (const e of paidExt) L.push(`- **${e.name}**: ${e.monthly}${e.annual !== e.monthly ? ` or ${e.annual}` : ""}. ${e.proposition}`);
    L.push(`- **${dtp.name}**: ${dtp.monthly} or ${dtp.annual}. ${dtp.proposition} Activate: ${facts.urls.developerTrustActivate}`, "");
    L.push(facts.editions.entitlementRule, "");
    L.push("**Capability parity, stated plainly:** this plugin inspects and routes in whatever host runs it. Mediation (the Local Trust Gate), retained history (Trust Epochs) and the other Pro capabilities run only in the VS Code extension. A plugin host cannot provide them, so this plugin does not claim them — and it does not withhold anything it can do.", "");
  }

  L.push("## Links", "", `- Documentation: ${facts.urls.gateway}`, `- Resolver (read-only public proof): ${facts.urls.resolver}`, `- TrustOps (setup and checkout for the optional paid products above): ${facts.urls.trustopsStart}`, `- Questions: ${facts.organisation.supportUrl}`);
  // Kiro Powers requires a privacy-policy link and a support contact in the README, and the
  // OpenAI directory asks for the same pages. One live page per plugin per kind.
  for (const page of policyPages(def)) L.push(`- ${page.label}: ${page.url}`);
  L.push("");
  L.push(`Generated by the ECZ-ID Plugin Foundry. Agent Plugins ${facts.specs.agentPlugins}. License: ${facts.organisation.license} (the Verifier package carries its own licence).`, "");
  return L.join("\n");
}

function buildPlugin(def) {
  const ctx = { ...facts, plugin: def };
  const bundle = def.review ? reviewBundle(def, ctx) : null;
  const dir = def.id;
  const version = defs.version;

  // Agent Plugins 1.0.0 manifest
  write(`${dir}/plugin.json`, json({
    $schema: facts.specs.pluginSchema,
    name: def.id,
    version,
    description: def.description,
    author: AUTHOR,
    homepage: def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs,
    repository: facts.organisation.estateUrl,
    license: facts.organisation.license,
    keywords: def.keywords
  }));
  // Claude Code manifest (same identity)
  write(`${dir}/.claude-plugin/plugin.json`, json({
    name: def.id, version, description: def.description, author: AUTHOR,
    homepage: def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs,
    repository: facts.organisation.estateUrl, license: facts.organisation.license, keywords: def.keywords
  }));
  // MCP servers (Agent Plugins shape, Claude/Copilot/Codex shape, Antigravity shape). Same servers, pinned.
  if (def.mcpServers.length) {
    const ap = {}, cl = {};
    for (const s of def.mcpServers) { ap[MCP_SERVERS[s].key] = MCP_SERVERS[s].agentPlugins; cl[MCP_SERVERS[s].key] = MCP_SERVERS[s].claude; }
    write(`${dir}/mcp.json`, json({ $schema: facts.specs.mcpSchema, mcpServers: ap }));
    write(`${dir}/.mcp.json`, json({ mcpServers: cl }));
    write(`${dir}/mcp_config.json`, json({ mcpServers: cl }));
  }
  // Logo (reused from the published VS Code extension icons) for marketplaces that require one.
  const logoSrc = join(here, "assets", `${def.id}.png`);
  if (existsSync(logoSrc)) {
    mkdirSync(join(OUT, dir, "assets"), { recursive: true });
    copyFileSync(logoSrc, join(OUT, dir, "assets", "logo.png"));
  }
  const homepage = def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs;
  // Cursor manifest: Cursor loads the Agent Plugins manifest as-is; this thin manifest adds the
  // logo and display name the Cursor Marketplace review requires (schemas/plugin.schema.json in cursor/plugins).
  write(`${dir}/.cursor-plugin/plugin.json`, json({
    name: def.id, displayName: def.displayName, version, description: def.description,
    author: { name: facts.organisation.name }, homepage, repository: facts.organisation.estateUrl,
    license: facts.organisation.license, logo: "assets/logo.png", keywords: def.keywords,
    skills: "./skills/", ...(def.mcpServers.length ? { mcpServers: "./mcp.json" } : {})
  }));
  // Codex / OpenAI manifest (.codex-plugin/plugin.json). Field order and the interface
  // shape are copied from the package OpenAI accepted for eczid-sbom-cra-readiness 0.1.1:
  // interface.logo and interface.composerIcon are required and must resolve to a square PNG
  // (>= 256x256 for the directory logo, >= 48x48 for the composer icon), and the OpenAI
  // public listing caps displayName and shortDescription at 30 characters each.
  write(`${dir}/.codex-plugin/plugin.json`, json({
    name: def.id, version, description: def.description,
    author: { name: facts.organisation.name, url: facts.urls.gateway },
    homepage, repository: facts.organisation.estateUrl, license: facts.organisation.license, keywords: def.keywords,
    skills: "./skills/", ...(def.mcpServers.length ? { mcpServers: "./.mcp.json" } : {}),
    interface: {
      displayName: def.displayName,
      shortDescription: def.openai.subtitle,
      longDescription: def.openai.longDescription,
      developerName: facts.organisation.name,
      category: OPENAI_CATEGORY,
      capabilities: OPENAI_CAPABILITIES,
      websiteURL: homepage,
      composerIcon: OPENAI_ICON,
      logo: OPENAI_ICON,
      defaultPrompt: [def.openai.defaultPrompt]
    }
  }));
  // Skills
  for (const skill of def.skills) {
    let body;
    if (skill === "ecz-id-verify") {
      body = fill(readFileSync(join(here, "templates", "skills", "ecz-id-verify.md"), "utf8"), ctx);
    } else {
      const ext = fillDeep(def.vscodeExtension, ctx);
      const subject = bundle.spec.displayName.replace(/^ECZ-ID /, "");
      const audience = def.id.includes("dora") ? "a DORA supervisory, audit or customer request" : def.id.includes("sbom") ? "the CRA reporting window" : "a reviewer, platform or counterparty";
      const extra = def.mcpServers.length
        ? `## Public proof\n\nWhen the review reports an ECZ-ID public proof reference, or the user names an ECZ-ID, use the read-only Verifier tools this plugin configures (\`${facts.verifier.tools.join("`, `")}\`) and report the ResultState and ReasonCodes exactly as returned. Absence of public proof is neutral.`
        : `## Regulatory wording\n\nQuote the regulation only as the review text does (article numbers and dates verified against EUR-Lex). Never state that the user is compliant, certified or ready; describe evidence observed, evidence not observed and what to review next.`;
      body = fill(readFileSync(join(here, "templates", "skills", "review-common.md"), "utf8"), { ...ctx, review: { subject, audience, extra }, extension: ext });
    }
    const description = bundle
      ? `${bundle.profile.question} Runs a local, filename-and-path-only evidence review and reports EVIDENCE OBSERVED / NOT OBSERVED, a deterministic Review Priority with reasons, why each class matters and what to review next. Use when asked about ${bundle.spec.displayName.replace(/^ECZ-ID /, "")} evidence, readiness, gaps or what to review next in a repository.`
      : `Check the public ECZ-ID Resolver posture of an MCP server, agent, API, package, domain or business with the read-only ECZ-ID Verifier tools, and explain ResultStates and ReasonCodes without scoring. Use when asked to check, verify or look up an ECZ-ID or public proof.`;
    const fm = [
      "---",
      `name: ${skill}`,
      `description: ${description.replace(/\n/g, " ")}`,
      `license: ${facts.organisation.license}`,
      "metadata:",
      `  author: ${facts.organisation.publisher}`,
      `  version: "${version}"`,
      `  ecz-id-plugin: ${def.id}`,
      "---",
      ""
    ].join("\n");
    write(`${dir}/skills/${skill}/SKILL.md`, fm + body);
    // OpenAI skill interface. icon_small / icon_large resolve from the SKILL ROOT, so the
    // logo must sit at skills/<skill>/assets/logo.png, never at skills/<skill>/agents/assets/.
    write(`${dir}/skills/${skill}/agents/openai.yaml`, [
      "interface:",
      `  display_name: ${yamlString(def.displayName)}`,
      `  short_description: ${yamlString(def.openai.subtitle)}`,
      `  icon_small: ${yamlString(OPENAI_ICON)}`,
      `  icon_large: ${yamlString(OPENAI_ICON)}`,
      `  default_prompt: ${yamlString(`Use $${skill} to ${lowerFirst(def.openai.defaultPrompt)}`)}`,
      "policy:",
      "  products:",
      ...OPENAI_PRODUCTS.map((p) => `    - ${p}`),
      "  allow_implicit_invocation: true",
      ""
    ].join("\n"));
    if (existsSync(logoSrc)) {
      mkdirSync(join(OUT, dir, "skills", skill, "assets"), { recursive: true });
      copyFileSync(logoSrc, join(OUT, dir, "skills", skill, "assets", "logo.png"));
    }
    if (bundle) {
      write(`${dir}/skills/${skill}/scripts/review.mjs`, reviewScript(bundle));
      write(`${dir}/skills/${skill}/references/evidence-classes.json`, json({ generatedFrom: bundle.syncedFrom ?? { definition: "foundry/plugins.json" }, detectors: bundle.spec.detectors.map((d) => ({ id: d.id, label: d.label, patterns: d.patterns })), guidance: bundle.profile.guidance }));
    }
  }
  write(`${dir}/README.md`, pluginReadme(def, ctx, bundle));
  return { def, version, homepage: def.vscodeExtension ? fill(def.vscodeExtension.page, ctx) : facts.urls.verifierDocs };
}

// ---- generate ----
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const built = defs.plugins.map(buildPlugin);

const entries = built.map(({ def, version, homepage }) => ({
  name: def.id,
  description: def.description,
  version,
  author: AUTHOR,
  homepage,
  repository: facts.organisation.estateUrl,
  license: facts.organisation.license,
  keywords: def.keywords,
  category: def.category
}));

const claudeMarketplace = {
  name: facts.organisation.marketplaceName,
  owner: { name: facts.organisation.name, url: facts.urls.gateway },
  metadata: { description: facts.organisation.marketplaceDescription, version: defs.version },
  plugins: entries.map((e) => ({ ...e, source: `./plugins/${e.name}` }))
};
const copilotMarketplace = {
  name: facts.organisation.marketplaceName,
  owner: { name: facts.organisation.name, url: facts.urls.gateway },
  metadata: { description: facts.organisation.marketplaceDescription, version: defs.version },
  plugins: entries.map((e) => ({ ...e, source: { source: "github", repo: facts.organisation.estateRepo, path: `plugins/${e.name}` } }))
};
// Cursor marketplace (.cursor-plugin/marketplace.json): bare directory sources, per cursor/plugins.
const cursorMarketplace = {
  name: facts.organisation.marketplaceName,
  owner: { name: facts.organisation.name },
  metadata: { description: facts.organisation.marketplaceDescription },
  plugins: entries.map((e) => ({ name: e.name, source: `plugins/${e.name}`, description: e.description }))
};
// Codex marketplace (.agents/plugins/marketplace.json): local sources with an explicit availability policy;
// every plugin here is read-only and needs no authentication.
const codexMarketplace = {
  name: facts.organisation.marketplaceName,
  interface: { displayName: "ECZ-ID Machine Trust" },
  plugins: entries.map((e) => ({
    name: e.name,
    source: { source: "local", path: `./plugins/${e.name}` },
    // Codex accepts only ON_INSTALL or ON_USE here (validated with codex-cli 0.153.0); these plugins
    // need no authentication at all, so ON_USE never prompts.
    policy: { installation: "AVAILABLE", authentication: "ON_USE" },
    category: "Developer Tools"
  }))
};
for (const d of [".claude-plugin", join(".github", "plugin"), ".cursor-plugin", join(".agents", "plugins")]) mkdirSync(join(root, d), { recursive: true });
writeFileSync(join(root, ".claude-plugin", "marketplace.json"), json(claudeMarketplace));
writeFileSync(join(root, ".github", "plugin", "marketplace.json"), json(copilotMarketplace));
writeFileSync(join(root, ".cursor-plugin", "marketplace.json"), json(cursorMarketplace));
writeFileSync(join(root, ".agents", "plugins", "marketplace.json"), json(codexMarketplace));
writeFileSync(join(OUT, "index.json"), json({ generatedBy: "foundry/build.mjs", agentPlugins: facts.specs.agentPlugins, version: defs.version, plugins: entries.map((e) => ({ name: e.name, description: e.description, path: `plugins/${e.name}` })) }));
console.log(`built ${built.length} plugins -> plugins/, marketplaces: .claude-plugin, .github/plugin, .cursor-plugin, .agents/plugins`);
