#!/usr/bin/env node
// ECZ-ID Plugin Foundry: Gemini CLI extension.
//
// Gemini CLI's gallery crawler indexes PUBLIC GitHub repositories carrying the topic
// `gemini-cli-extension`, and requires `gemini-extension.json` at the ABSOLUTE ROOT of
// the repository or of a release archive. One repository is therefore one extension and
// one gallery entry, so the whole estate ships as a single extension rather than six.
// Skills are auto-discovered at `skills/<skill-name>/SKILL.md` relative to the extension
// root; no manifest field declares them.
//
// Everything here is generated from the same plugins/ tree as every other host, so the
// estate stays canonical: no forked source trees, nothing hand-maintained.
//
// Usage: node foundry/gemini.mjs [--out <dir>]
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync, existsSync, statSync } from "node:fs";
import { dirname, join, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { zipWrite } from "./zip.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const facts = JSON.parse(readFileSync(join(here, "product-facts.json"), "utf8"));
const defs = JSON.parse(readFileSync(join(here, "plugins.json"), "utf8"));

export const EXTENSION_NAME = "eczid-machine-trust";
const outArg = process.argv.indexOf("--out");
const OUT = outArg > 0 ? resolve(process.argv[outArg + 1]) : join(root, "dist", "gemini");

const listFilesUnder = (dir) => {
  const out = [];
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else out.push(p);
    }
  };
  if (existsSync(dir) && statSync(dir).isDirectory()) walk(dir);
  return out;
};
const posix = (p) => p.split("\\").join("/");

/** The context file Gemini CLI loads for every session in a workspace using this extension. */
function contextFile() {
  const L = [`# ECZ-ID Machine Trust`, "", facts.organisation.marketplaceDescription, "", "## Doctrine", ""];
  for (const d of facts.doctrine) L.push(`- ${d}`);
  L.push("", "## Skills in this extension", "");
  for (const def of defs.plugins) L.push(`- \`${def.skills.join("`, `")}\` — ${def.displayName}: ${def.openai.subtitle}.`);
  L.push("", `Documentation: ${facts.urls.gateway}`, "");
  return L.join("\n");
}

function readme() {
  const L = [`# ECZ-ID Machine Trust — Gemini CLI extension`, "",
    facts.organisation.marketplaceDescription, "",
    "## Install", "", "```", `gemini extensions install ${facts.organisation.estateUrl}`, "```", "",
    "## Skills", "",
    "| Skill | Product | What it answers |", "|---|---|---|"];
  for (const def of defs.plugins) {
    L.push(`| \`${def.skills[0]}\` | ${def.displayName} | ${def.openai.subtitle} |`);
  }
  L.push("", "## What every skill does and does not do", "");
  for (const d of facts.doctrine) L.push(`- ${d}`);
  L.push("", `Generated by the ECZ-ID Plugin Foundry from ${facts.organisation.estateUrl}. Licence: ${facts.organisation.license}.`, "");
  return L.join("\n");
}

/** @returns {{name: string, data: Buffer}[]} extension files, manifest first, archive order. */
export function stageExtension() {
  const entries = [];
  const add = (name, data) => entries.push({ name, data: Buffer.isBuffer(data) ? data : Buffer.from(data) });

  // One stdio MCP server, the same pinned read-only Verifier every other host gets.
  const mcpServers = {
    [`ecz-id-verifier`]: {
      command: "npx",
      args: ["-y", `${facts.verifier.npm}@${facts.verifier.version}`, facts.verifier.stdioBin]
    }
  };
  add("gemini-extension.json", JSON.stringify({
    name: EXTENSION_NAME,
    version: defs.version,
    description: facts.organisation.marketplaceDescription,
    contextFileName: "GEMINI.md",
    mcpServers
  }, null, 2) + "\n");
  add("GEMINI.md", contextFile());
  add("README.md", readme());
  add("LICENSE.md", readFileSync(join(root, "LICENSE.md")));

  const seen = new Set();
  for (const def of defs.plugins) {
    for (const skill of def.skills) {
      if (seen.has(skill)) throw new Error(`two plugins ship a skill named "${skill}"; skills are flattened into one extension`);
      seen.add(skill);
      const sdir = join(root, "plugins", def.id, "skills", skill);
      for (const f of listFilesUnder(sdir)) {
        const rel = posix(relative(sdir, f));
        // agents/openai.yaml is the OpenAI listing interface; it has no meaning here.
        if (rel === "agents/openai.yaml") continue;
        add(`skills/${skill}/${rel}`, readFileSync(f));
      }
    }
  }
  return entries;
}

export function buildExtension({ outDir = OUT, write = true } = {}) {
  const entries = stageExtension();
  const buf = zipWrite(entries);
  if (write) {
    const dir = join(outDir, EXTENSION_NAME);
    rmSync(dir, { recursive: true, force: true });
    for (const e of entries) {
      const p = join(dir, e.name);
      mkdirSync(dirname(p), { recursive: true });
      writeFileSync(p, e.data);
    }
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(outDir, `${EXTENSION_NAME}.zip`), buf);
  }
  return {
    name: EXTENSION_NAME,
    version: defs.version,
    dir: join(outDir, EXTENSION_NAME),
    zip: join(outDir, `${EXTENSION_NAME}.zip`),
    bytes: buf.length,
    sha256: createHash("sha256").update(buf).digest("hex"),
    entries: entries.map((e) => e.name)
  };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const b = buildExtension();
  console.log(`${b.name} ${b.version}: ${b.entries.length} files, ${b.bytes} bytes, sha256 ${b.sha256.slice(0, 16)}…`);
  console.log(`  directory: ${posix(relative(root, b.dir))}/`);
  console.log(`  archive:   ${posix(relative(root, b.zip))}  (gemini-extension.json at the archive root)`);
}
